# Use new trusty images, should yield newer compilers and packages
# Copied from https://github.com/genbattle/dkm/blob/9c893efb556516f4b121a6201b66e000f838dd59/.travis.yml
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER=g++-4.9
        - CXX=g++-4.9
        - CC=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - CXX=g++-5
        - CC=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - COMPILER=clang++-3.6
        - CXX=clang++-3.6
        - CC=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - COMPILER=clang++-3.7
        - CXX=clang++-3.7
        - CC=clang-3.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
  - mkdir build

script: cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ./ut
