# Use new trusty images, should yield newer compilers and packages
# Copied from https://github.com/genbattle/dkm/blob/9c893efb556516f4b121a6201b66e000f838dd59/.travis.yml
sudo: required
dist: precise
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - CC_COMPILER=gcc-5
        - CXX_COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - CC_OMPILER=clang-3.7
        - CXX_OMPILER=clang++-3.7

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
  - mkdir build
  - export CC=$CC_COMPILER
  - export CXX=$CXX_COMPILER

script: cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make && ./ut
